Update TYPO3 12
slub/slub_digitalcollections pull request #94
Opened 2024-10-21 15:49 UTC by markusweigelt

2024-10-24 12:33 UTC, stweil reviewed
ext_emconf.php also needs an update to allow TYPO3 12.

2024-10-25 17:30 UTC, stweil commented
> ext_emconf.php also needs an update to allow TYPO3 12.

This was done in commit 118c2a3d1104dc91e814a27b2d2482f6778821d0.

2024-10-25 17:39 UTC, stweil approved these changes
This code works for me in my test with TYPO3 12.4 and DFG Viewer. Thanks!

2024-11-16 17:26 UTC, stweil approved these changes
I now tested the latest version of this pull request again with the [related pull request for the DFG Viewer](https://github.com/slub/dfg-viewer/pull/322), and it works for me.

2024-12-10 15:34 UTC, fschoelzel commented
Is there any news on this yet? When is this feature going to be merged into a new Version?

2024-12-10 16:48 UTC, markusweigelt commented
@fschoelzel Afaik, this is still waiting for internal error resolution in the old state. @beatrycze-volk probably knows more about it?

2025-02-11 08:27 UTC, beatrycze-volk requested changes
Requested changes are for keeping compatibility with Kitodo.Presentation.

2025-02-11 08:27 UTC, beatrycze-volk commented on composer.json
>      "php": "7.4 - 8.3",
Please change to `"php": "8.1 - 8.3"`

2025-02-11 08:27 UTC, beatrycze-volk commented on composer.json
>      "kitodo/presentation": "^5.0|dev-main"
At the moment it needs to be change to `dev-main` until the 6.0 is not released.

2025-02-11 08:27 UTC, beatrycze-volk commented on ext_emconf.php
> +            'php' => '7.4.0-8.3.99',
Please change into `'php' => '8.1.0-8.3.99'`

2025-02-11 08:53 UTC, markusweigelt commented on composer.json
>      "kitodo/presentation": "^5.0|dev-main"
I don't quite understand what exactly needs to be adjusted? Remove the ^5.0?

2025-02-11 08:57 UTC, beatrycze-volk commented on composer.json
>      "kitodo/presentation": "^5.0|dev-main"
Yes

2025-02-12 15:56 UTC, beatrycze-volk commented
@markusweigelt please solve conflicts

2025-02-13 13:19 UTC, beatrycze-volk approved these changes

2025-02-13 13:19 UTC, merged